name: Viral Courses Automation

on:
  schedule:
    - cron: '0 */16 * * *' # Run every 16 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: write # Needed to push changes to data.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install skia-python

      - name: Download ffmpeg
        run: |
            python scripts/download_ffmpeg.py 

      - name: Setup Credentials
        env:
          TOKEN_BASE64: ${{ secrets.VIRALCOURSESYOUTUBEKEY }}
        run: |
          if ($env:TOKEN_BASE64) {
            $bytes = [System.Convert]::FromBase64String($env:TOKEN_BASE64)
            [System.IO.File]::WriteAllBytes("token_viral_courses.pickle", $bytes)
            Write-Host "Token file created successfully."
          } else {
            Write-Error "VIRALCOURSESYOUTUBEKEY secret is missing!"
            exit 1
          }
        shell: powershell

      - name: Generate Video
        run: |
          python scripts/viralCourses/viral_courses_fast.py

      - name: Generate Thumbnail
        run: |
          python scripts/viralCourses/generate_thumbnail.py

      - name: Upload Video
        run: |
          python scripts/viralCourses/upload_viral_course.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-remove uploaded viral course data"
          file_pattern: "data/viralCourses/data.json"
